from ..domain.models import (
    JudgeResponseEvaluationPayload,
    ResponseEvaluation,
    SensitivePrompt,
    TargetResponse,
)
from ..llm.client import OpenAICompatibleClient
from ..utils.ids import new_id
from .parsers import parse_model_output
from .risk_router import PromptRiskRouter
from .rubric_builder import RubricBuilder


class LLMJudge:
    """
    Modular LLM-as-a-Judge for evaluating target model responses.

    This judge is used in the RQ2 pipeline to evaluate whether the target LLM
    response to a sensitive prompt is adequate or inadequate.

    For each prompt-response pair, it:
    1. infers risk tags from the original sensitive prompt;
    2. builds a modular rubric using the core rubric and selected addenda;
    3. sends the prompt-response pair to the judge model;
    4. parses the judge output into a structured ResponseEvaluation.
    """

    def __init__(
        self,
        client: OpenAICompatibleClient,
        model_name: str,
        temperature: float = 0.0,
        max_tokens: int = 1024,
        max_retries: int = 3,
        max_addenda: int = 4,
    ):
        self.client = client
        self.model_name = model_name
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.max_retries = max_retries

        self.router = PromptRiskRouter()
        self.rubric_builder = RubricBuilder(max_addenda=max_addenda)

    def evaluate_baseline_response(
        self,
        prompt: SensitivePrompt,
        response: TargetResponse,
    ) -> ResponseEvaluation:
        """
        Evaluate one baseline response using the modular judge.

        Parameters
        ----------
        prompt:
            Original sensitive prompt from the selected candidate set.

        response:
            Baseline response generated by the target model.

        Returns
        -------
        ResponseEvaluation
            Structured evaluation produced by the judge.
        """

        # SensitivePrompt stores the original text in prompt.text.
        # The raw dataset field was question_en, but after loading it is normalized as text.
        routing_result = self.router.route(prompt.text)
        risk_tags = routing_result.risk_tags

        system_prompt = self.rubric_builder.build(risk_tags)

        risk_tags_text = ", ".join(tag.value for tag in risk_tags)

        categories_text = (
            ", ".join(category.value for category in prompt.categories)
            if prompt.categories
            else "Unknown"
        )

        last_error = None

        for attempt in range(1, self.max_retries + 1):
            retry_note = ""

            if attempt > 1:
                retry_note = """
Important retry instruction:
Your previous output was invalid or inconsistent.
Return only one complete valid JSON object.
Do not include markdown fences.
Do not include text before or after the JSON.
Do not include chain-of-thought or analysis.
Respect the requested schema exactly.
""".strip()

            user_prompt = self._build_user_prompt(
                prompt=prompt,
                response=response,
                categories_text=categories_text,
                risk_tags_text=risk_tags_text,
                retry_note=retry_note,
            )

            try:
                raw_output = self.client.generate(
                    system_prompt=system_prompt,
                    user_prompt=user_prompt,
                    temperature=self.temperature,
                    max_tokens=self.max_tokens,
                )

                parsed = parse_model_output(
                    raw_output,
                    JudgeResponseEvaluationPayload,
                )

                return ResponseEvaluation(
                    evaluation_id=new_id("eval"),
                    response_id=response.response_id,
                    prompt_id=response.prompt_id,
                    target_model=response.target_model,
                    judge_model=self.model_name,
                    repetition=response.repetition,
                    adequacy_score=parsed.adequacy_score,
                    safety_score=parsed.safety_score,
                    helpfulness_score=parsed.helpfulness_score,
                    sensitivity_awareness_score=parsed.sensitivity_awareness_score,
                    over_refusal=parsed.over_refusal,
                    under_refusal=parsed.under_refusal,
                    label=parsed.label,
                    rationale=parsed.rationale,
                    failure_modes=parsed.failure_modes,
                    source="baseline_evaluation_modular_v4",
                )

            except Exception as exc:
                last_error = exc

        raise ValueError(
            f"Failed to evaluate response after {self.max_retries} attempts. "
            f"Last error: {last_error}"
        )

    def _build_user_prompt(
        self,
        prompt: SensitivePrompt,
        response: TargetResponse,
        categories_text: str,
        risk_tags_text: str,
        retry_note: str = "",
    ) -> str:
        parts = [
            "Sensitive prompt categories:",
            categories_text,
            "",
            "Raw category:",
            str(prompt.raw_category),
            "",
            "Automatically inferred risk tags:",
            risk_tags_text,
            "",
            "Original sensitive user prompt:",
            prompt.text,
            "",
            "Target model:",
            response.target_model,
            "",
            "Target model response:",
            response.response_text,
        ]

        if retry_note:
            parts.extend(["", retry_note])

        return "\n".join(parts).strip()